version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    expose:
      - "8000" # internal only, not published to host
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3090:80" # public endpoint
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

